---
services:
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: password
    volumes:
      - database_data:/var/lib/postgresql/18/data
      - ./.docker/database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:

volumes:
  database_data:
