---
name: Workastra Platform

on:
  pull_request:
  push:
    branches:
      - v0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  JAVA_VERSION: 26
  JAVA_DISTRIBUTION: corretto

jobs:
  qodana:
    name: Qodana Scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
      checks: write
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
      - uses: JetBrains/qodana-action@v2026.1.3
        with:
          pr-mode: false

  verification:
    name: "[${{ matrix.module }}] JVM build & test"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        module: [console, iam, migration]
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Set up JAVA
        uses: actions/setup-java@v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Test JVM
        run: ./gradlew --no-daemon :${{ matrix.module }}:check

      - name: Build JVM
        run: ./gradlew --no-daemon :${{ matrix.module }}:build
